function handleFunkcionarjiPage() {
  const selectMember = document.getElementById("official-member");
  const selectRole = document.getElementById("official-role");
  const selectBody = document.getElementById("official-body");
  const selectMandate = document.getElementById("official-mandate");
  const filterMandate = document.getElementById("official-filter-mandate");
  const tbody = document.getElementById("officials-tbody");
  const form = document.getElementById("official-form");
  const mandateForm = document.getElementById("mandate-form");
  const mandateStart = document.getElementById("mandate-start");
  const mandateEnd = document.getElementById("mandate-end");
  const btnPrint = document.getElementById("btn-print-officials");
  const aktivnoLetoEl = document.getElementById("aktivno-leto");

  if (aktivnoLetoEl) aktivnoLetoEl.textContent = AktivnoLeto();
  if (!selectMember || !selectRole || !selectBody || !selectMandate || !filterMandate || !tbody || !form || !mandateForm) return;

  const MANDATES_KEY = "rd_official_mandates";

  const BODIES = {
    "upravni-odbor": {
      label: "Upravni odbor",
      roles: ["Predsednik", "Tajnik", "Gospodar", "Član"],
      order: 1,
    },
    "disciplinski-tozilec": {
      label: "Disciplinski tožilec",
      roles: ["Tožilec", "Namestnik"],
      order: 2,
    },
    "disciplinsko-sodisce": {
      label: "Disciplinsko sodišče",
      roles: ["Član", "Namestnik"],
      order: 3,
    },
  };

  const ROLE_ORDER = ["Predsednik", "Tajnik", "Gospodar", "Tožilec", "Član", "Namestnik"];
  const safe = (v) => (v == null ? "" : String(v));

  ensureDefaultMandate();
  normalizeFirstMandate();
  migrateLegacyOfficials();
  fillMemberSelect();
  fillRoleSelect();
  fillMandateSelects();
  renderTable();

  selectBody.addEventListener("change", () => {
    fillRoleSelect();
    renderTable();
  });

  selectMandate.addEventListener("change", () => {
    filterMandate.value = selectMandate.value;
    renderTable();
  });

  filterMandate.addEventListener("change", () => {
    selectMandate.value = filterMandate.value;
    renderTable();
  });

  mandateForm.addEventListener("submit", (event) => {
    event.preventDefault();
    addMandate();
  });

  form.addEventListener("submit", (event) => {
    event.preventDefault();
    addOfficial();
  });

  btnPrint?.addEventListener("click", printCurrentMandate);

  function activeMembers() {
    return getMembers().filter((m) => !m.arhiviran);
  }

  function getMandates() {
    return getJSON(MANDATES_KEY, []);
  }

  function saveMandates(list) {
    setJSON(MANDATES_KEY, list);
  }

  function mandateLabel(mandate) {
    if (!mandate) return "Brez mandata";
    return `${mandate.startYear}-${mandate.endYear}`;
  }

  function ensureDefaultMandate() {
    const mandates = getMandates();
    if (mandates.length) return;

    saveMandates([
      {
        id: Date.now(),
        startYear: 2025,
        endYear: 2030,
        createdAt: new Date().toISOString(),
      },
    ]);
  }

  function normalizeFirstMandate() {
    const mandates = sortMandates(getMandates());
    const first = mandates[0];
    if (!first) return;

    const isAutoGeneratedOldMandate = Number(first.startYear) === 2026 && Number(first.endYear) === 2030;
    const alreadyHasCorrectMandate = mandates.some((m) => Number(m.startYear) === 2025 && Number(m.endYear) === 2030);
    if (!isAutoGeneratedOldMandate || alreadyHasCorrectMandate) return;

    const updatedMandates = mandates.map((mandate) =>
      mandate.id === first.id ? { ...mandate, startYear: 2025, endYear: 2030 } : mandate
    );
    saveMandates(updatedMandates);

    const updatedOfficials = getOfficials().map((official) => {
      const belongsToFirst =
        Number(official.mandateId) === Number(first.id) ||
        (Number(official.mandateStart) === 2026 && Number(official.mandateEnd) === 2030);
      return belongsToFirst ? { ...official, mandateStart: 2025, mandateEnd: 2030 } : official;
    });
    saveOfficials(updatedOfficials);
  }

  function migrateLegacyOfficials() {
    const mandates = sortMandates(getMandates());
    const fallbackMandate = mandates[0];
    if (!fallbackMandate) return;

    let changed = false;
    const officials = getOfficials().map((official) => {
      if (official.mandateId && official.body) return official;
      changed = true;
      const body = official.body || inferBodyFromRole(official.role);
      return {
        ...official,
        mandateId: official.mandateId || fallbackMandate.id,
        mandateStart: official.mandateStart || fallbackMandate.startYear,
        mandateEnd: official.mandateEnd || fallbackMandate.endYear,
        body,
        role: normalizeLegacyRole(official.role, body),
      };
    });

    if (changed) saveOfficials(officials);
  }

  function inferBodyFromRole(role) {
    if (role === "Tožilec") return "disciplinski-tozilec";
    if (String(role || "").toLowerCase().includes("disciplinsk")) return "disciplinsko-sodisce";
    return "upravni-odbor";
  }

  function normalizeLegacyRole(role, body) {
    if (role === "Član UO") return "Član";
    if (String(role || "").toLowerCase().includes("disciplinsk")) return "Član";
    if ((BODIES[body]?.roles || []).includes(role)) return role;
    return BODIES[body]?.roles?.[0] || role || "Član";
  }

  function addMandate() {
    const startYear = Number(mandateStart.value);
    const endYear = Number(mandateEnd.value);

    if (!Number.isFinite(startYear) || !Number.isFinite(endYear) || startYear < 1900 || endYear < startYear) {
      alert("Vpiši pravilno mandatno obdobje.");
      return;
    }

    const mandates = getMandates();
    if (mandates.some((m) => Number(m.startYear) === startYear && Number(m.endYear) === endYear)) {
      alert("To mandatno obdobje že obstaja.");
      return;
    }

    const mandate = {
      id: Date.now(),
      startYear,
      endYear,
      createdAt: new Date().toISOString(),
    };

    mandates.unshift(mandate);
    saveMandates(sortMandates(mandates));
    mandateForm.reset();
    fillMandateSelects(mandate.id);
    addHistory("Funkcionarji", `Dodano mandatno obdobje ${mandateLabel(mandate)}.`);
  }

  function sortMandates(list) {
    return list.slice().sort((a, b) => Number(b.startYear || 0) - Number(a.startYear || 0));
  }

  function fillMandateSelects(selectedId) {
    const mandates = sortMandates(getMandates());
    const selected = selectedId || selectMandate.value || mandates[0]?.id || "";
    const options = mandates.map((m) => `<option value="${m.id}">${escapeHtml(mandateLabel(m))}</option>`).join("");
    selectMandate.innerHTML = options;
    filterMandate.innerHTML = options;
    selectMandate.value = String(selected);
    filterMandate.value = String(selected);

    const current = mandates.find((m) => String(m.id) === String(selectMandate.value)) || mandates[0];
    if (current) {
      mandateStart.value = Number(current.endYear || current.startYear || currentYear()) + 1;
      mandateEnd.value = Number(mandateStart.value) + 4;
    }
  }

  function fillMemberSelect() {
    const members = activeMembers().slice().sort(sortMembers);

    selectMember.innerHTML = members
      .map((m) => `<option value="${m.id}">${escapeHtml(`${m.priimek || ""} ${m.ime || ""} (št. ${m.clanska || "-"})`)}</option>`)
      .join("");

    if (!members.length) {
      selectMember.innerHTML = `<option value="">Ni aktivnih članov</option>`;
    }
  }

  function fillRoleSelect() {
    const body = BODIES[selectBody.value] || BODIES["upravni-odbor"];
    selectRole.innerHTML = body.roles.map((role) => `<option value="${escapeAttr(role)}">${escapeHtml(role)}</option>`).join("");
  }

  function addOfficial() {
    const memberId = Number(selectMember.value);
    const mandateId = Number(selectMandate.value);
    const body = selectBody.value;
    const role = (selectRole.value || "").trim();

    if (!memberId || !mandateId || !body || !role) {
      alert("Izberi mandat, organ, funkcijo in člana.");
      return;
    }

    const mandate = getMandates().find((m) => Number(m.id) === mandateId);
    if (!mandate) {
      alert("Izbrano mandatno obdobje ne obstaja.");
      return;
    }

    const officials = getOfficials();
    const duplicate = officials.some(
      (o) => Number(o.memberId) === memberId && Number(o.mandateId) === mandateId && o.body === body && o.role === role
    );

    if (duplicate) {
      alert("Ta član je v izbranem mandatu že dodan na to funkcijo.");
      return;
    }

    officials.push({
      id: Date.now(),
      memberId,
      mandateId,
      mandateStart: mandate.startYear,
      mandateEnd: mandate.endYear,
      body,
      role,
      createdAt: new Date().toISOString(),
    });
    saveOfficials(officials);

    const member = getMembers().find((m) => m.id === memberId);
    addHistory(
      "Funkcionarji",
      `Dodan funkcionar: ${member ? `${member.priimek || ""} ${member.ime || ""}`.trim() : "neznan član"} (${BODIES[body]?.label || body}, ${role}, mandat ${mandateLabel(mandate)}).`
    );

    renderTable();
  }

  function joinedOfficials() {
    const members = getMembers();
    const mandates = getMandates();
    const selectedMandate = Number(filterMandate.value || selectMandate.value);

    return getOfficials()
      .map((official) => {
        const mandate =
          mandates.find((m) => Number(m.id) === Number(official.mandateId)) ||
          mandates.find((m) => Number(m.startYear) === Number(official.mandateStart) && Number(m.endYear) === Number(official.mandateEnd)) ||
          null;
        return {
          ...official,
          mandate,
          member: members.find((m) => Number(m.id) === Number(official.memberId)) || null,
        };
      })
      .filter((official) => {
        if (!selectedMandate) return true;
        return Number(official.mandate?.id || official.mandateId) === selectedMandate;
      })
      .sort(sortOfficials);
  }

  function sortOfficials(a, b) {
    const bodyDiff = (BODIES[a.body]?.order || 99) - (BODIES[b.body]?.order || 99);
    if (bodyDiff !== 0) return bodyDiff;

    const roleDiff = roleRank(a.role) - roleRank(b.role);
    if (roleDiff !== 0) return roleDiff;

    return sortMembers(a.member || {}, b.member || {});
  }

  function roleRank(role) {
    const index = ROLE_ORDER.indexOf(role);
    return index === -1 ? 999 : index;
  }

  function renderTable() {
    const list = joinedOfficials();
    tbody.innerHTML = "";

    if (!list.length) {
      tbody.innerHTML = `
        <tr>
          <td colspan="9" style="padding:14px; text-align:center; opacity:.75;">
            V izbranem mandatu še ni vnešenih funkcionarjev.
          </td>
        </tr>
      `;
      return;
    }

    let lastBody = "";
    let bodyIndex = 0;

    list.forEach((official) => {
      const bodyLabel = BODIES[official.body]?.label || official.body || "Drugo";
      if (bodyLabel !== lastBody) {
        lastBody = bodyLabel;
        bodyIndex = 0;
        const section = document.createElement("tr");
        section.className = "officials-section-row";
        section.innerHTML = `<td colspan="9">${escapeHtml(bodyLabel)}</td>`;
        tbody.appendChild(section);
      }

      bodyIndex += 1;
      tbody.appendChild(renderOfficialRow(official, bodyIndex, bodyLabel));
    });
  }

  function renderOfficialRow(official, index, bodyLabel) {
    const member = official.member;
    const name = member ? `${safe(member.priimek)} ${safe(member.ime)}`.trim() : "(član ne obstaja)";
    const tel = safe(member?.telefon).trim();
    const email = safe(member?.email).trim();
    const naslov = safe(member?.naslov).trim();
    const kraj = [member?.posta, member?.kraj].filter(Boolean).join(" ");

    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td class="col-zapst">${index}</td>
      <td>${escapeHtml(bodyLabel)}</td>
      <td>${escapeHtml(official.role || "")}</td>
      <td>${escapeHtml(name)}</td>
      <td>${tel ? `<a href="tel:${escapeAttr(tel)}">${escapeHtml(tel)}</a>` : ""}</td>
      <td>${email ? `<a href="mailto:${escapeAttr(email)}">${escapeHtml(email)}</a>` : ""}</td>
      <td>${escapeHtml(naslov)}</td>
      <td>${escapeHtml(kraj)}</td>
      <td class="table-actions">
        <button type="button" class="tool-btn danger" data-action="delete">Odstrani</button>
      </td>
    `;

    tr.querySelector('[data-action="delete"]')?.addEventListener("click", () => {
      if (!confirm("Odstranim funkcionarja iz mandata?")) return;

      saveOfficials(getOfficials().filter((item) => item.id !== official.id));
      addHistory("Funkcionarji", `Odstranjen funkcionar: ${name} (${official.role || ""}).`);
      renderTable();
    });

    return tr;
  }

  function printCurrentMandate() {
    const mandate = getMandates().find((m) => String(m.id) === String(filterMandate.value));
    const list = joinedOfficials();
    const title = `Funkcionarji RD Mozirje - mandat ${mandateLabel(mandate)}`;
    const grouped = Object.keys(BODIES)
      .map((bodyKey) => ({
        body: BODIES[bodyKey],
        rows: list.filter((item) => item.body === bodyKey),
      }))
      .filter((group) => group.rows.length);

    const win = window.open("", "_blank");
    if (!win) {
      alert("Brskalnik je blokiral odpiranje predogleda. Dovoli pojavna okna za to stran.");
      return;
    }

    win.document.write(`
      <html lang="sl">
        <head>
          <meta charset="UTF-8">
          <title>${escapeHtml(title)}</title>
          <style>
            @page { size: A4 portrait; margin: 12mm; }
            body { font-family: "Times New Roman", serif; color: #000; }
            h1 { text-align: center; font-size: 18px; margin: 0 0 16px; text-transform: uppercase; }
            h2 { font-size: 16px; margin: 18px 0 4px; text-transform: uppercase; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 12px; }
            th, td { border: 1px solid #000; padding: 3px 6px; text-align: left; vertical-align: top; }
            th { font-weight: 700; text-align: center; }
            td:first-child { width: 44px; text-align: center; }
            td:nth-child(2) { width: 38%; font-weight: 700; }
            td:nth-child(3) { font-weight: 700; text-transform: uppercase; }
          </style>
        </head>
        <body>
          <h1>${escapeHtml(title)}</h1>
          ${
            grouped.length
              ? grouped
                  .map(
                    (group) => `
                      <h2>${escapeHtml(group.body.label)}</h2>
                      <table>
                        <thead>
                          <tr>
                            <th>zap. št.</th>
                            <th>predlagana funkcija</th>
                            <th>priimek in ime</th>
                          </tr>
                        </thead>
                        <tbody>
                          ${group.rows
                            .map((official, index) => {
                              const member = official.member;
                              const name = member ? `${member.priimek || ""} ${member.ime || ""}`.trim() : "";
                              return `
                                <tr>
                                  <td>${index + 1}</td>
                                  <td>${escapeHtml(official.role || "")}</td>
                                  <td>${escapeHtml(name)}</td>
                                </tr>
                              `;
                            })
                            .join("")}
                        </tbody>
                      </table>
                    `
                  )
                  .join("")
              : "<p>Za izbrani mandat ni vnešenih funkcionarjev.</p>"
          }
          <script>window.addEventListener("load", () => window.print());</script>
        </body>
      </html>
    `);
    win.document.close();
    addHistory("Funkcionarji", `Pripravljen tisk funkcionarjev za mandat ${mandateLabel(mandate)}.`);
  }
}

function sortMembers(a, b) {
  const last = String(a?.priimek || "").localeCompare(String(b?.priimek || ""), "sl", { sensitivity: "base" });
  if (last !== 0) return last;
  return String(a?.ime || "").localeCompare(String(b?.ime || ""), "sl", { sensitivity: "base" });
}

function escapeAttr(s) {
  return String(s).replaceAll('"', "&quot;").replaceAll("'", "&#039;");
}

function escapeHtml(str) {
  return String(str ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

document.addEventListener("DOMContentLoaded", () => {
  ensureDemoData();

  const user = requireAuth({ pageModuleKey: "funkcionarji" });
  if (!user) return;

  initHeader(user);
  renderAppNav(user, "funkcionarji");
  startReminderWatcher();

  handleFunkcionarjiPage();
});
